Implement initial E2E test suite setup
Signed-off-by: wen.rui <wen.rui@daocloud.io>

diff --git a/.github/workflows/call-e2e.yaml b/.github/workflows/call-e2e.yaml
--- a/.github/workflows/call-e2e.yaml
+++ b/.github/workflows/call-e2e.yaml
@@ -4,15 +4,75 @@ on:
   workflow_call:
     inputs:
       ref:
+        description: 'Reference id to run tests'
         required: true
         type: string
-permissions: write-all
+      type:
+        description: 'E2E type'
+        required: true
+        type: string
+        default: pullrequest
 
 jobs:
-  e2e:
-    runs-on: ubuntu-latest
+  e2e-test:
+    strategy:
+      matrix:
+        include:
+          - device: nvidia
+            type: tesla-p4
+#          - device: nvidia
+#            type: rtx-4090
+#          - device: huawei
+#            type: ascend-910b
+    runs-on: [ "${{ matrix.device }}", "${{ matrix.type }}" ]
+    environment: ${{ matrix.device }}
+    env:
+      E2E_TYPE: ${{ inputs.type }}
     steps:
-      - name: e2e test
-        # https://github.com/actions/virtual-environments/issues/709
+      - name: checkout code
+        uses: actions/checkout@v4
+
+      - name: install Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: "1.21"
+
+      - name: setup e2e env
         run: |
-          echo "Need to add e2e test"
+          make e2e-env-setup
+
+      - name: download hami helm
+        if: inputs.type == 'pullrequest'
+        uses: actions/download-artifact@v4
+        with:
+          name: chart_package_artifact
+          path: charts/
+
+      - name: download hami image
+        if: inputs.type == 'pullrequest'
+        uses: actions/download-artifact@v4
+        with:
+          name: hami-image
+          path: ./image
+
+      - name: load e2e image
+        if: inputs.type == 'pullrequest'
+        run: |
+          echo "Loading Docker image from image.tar..."
+          if [ -z "${VSPHERE_GPU_VM_IP}" ]; then
+            echo "Error: VSPHERE_GPU_VM_IP is not defined!"
+            exit 1
+          fi
+          scp ./image/image.tar root@$VSPHERE_GPU_VM_IP:/home/
+          ssh root@$VSPHERE_GPU_VM_IP "nerdctl load -i /home/image.tar"
+          ssh root@$VSPHERE_GPU_VM_IP "nerdctl image ls | grep hami"
+
+      - name: deploy hami helm
+        env:
+          HAMI_VERSION: ${{ inputs.ref }}
+        run: |
+          make helm-deploy
+
+      - name: e2e test
+        run: |
+          make e2e-test
